on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - "**/*.py"
      - "LICENSE"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [ '1.22.5' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get .
      - name: Test
        run: |
          go install github.com/jstemmer/go-junit-report/v2@latest
          go test -short -timeout 120s -race -count 1 -v ./... 2>&1 | go-junit-report -set-exit-code -iocopy -out "${{ github.workspace }}/report.xml"
      - name: Test summary
        uses: test-summary/action@v2
        with:
          paths: |
            ${{ github.workspace }}/report.xml
        if: always()
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}